//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstallerUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstallerUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Install.
        /// </summary>
        public static string AppSelectionScreenHeading {
            get {
                return ResourceManager.GetString("AppSelectionScreenHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for software install.
        /// </summary>
        public static string CABeforeInstallationBegin {
            get {
                return ResourceManager.GetString("CABeforeInstallationBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for software uninstall.
        /// </summary>
        public static string CABeforeUninstallationBegin {
            get {
                return ResourceManager.GetString("CABeforeUninstallationBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are installing the software.
        /// </summary>
        public static string CAInstalling {
            get {
                return ResourceManager.GetString("CAInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling Installation.
        /// </summary>
        public static string CancelInstallation {
            get {
                return ResourceManager.GetString("CancelInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Exit.
        /// </summary>
        public static string CancelInstallationCaption {
            get {
                return ResourceManager.GetString("CancelInstallationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling Uninstallation.
        /// </summary>
        public static string CancelUninstallation {
            get {
                return ResourceManager.GetString("CancelUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are uninstalling the software.
        /// </summary>
        public static string CAUninstalling {
            get {
                return ResourceManager.GetString("CAUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Install.
        /// </summary>
        public static string ConfigureLocalSQLServerViewHeading {
            get {
                return ResourceManager.GetString("ConfigureLocalSQLServerViewHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure SQL Server Instance.
        /// </summary>
        public static string ConfigureSqlServerInstance {
            get {
                return ResourceManager.GetString("ConfigureSqlServerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will uninstall Immo Pro and all of its components from your computer..
        /// </summary>
        public static string DisplayMessageOnUninstallation {
            get {
                return ResourceManager.GetString("DisplayMessageOnUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to terms of services.
        /// </summary>
        public static string EulaCheckBoxContent {
            get {
                return ResourceManager.GetString("EulaCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-USER LICENSE AGREEMENT (EULA).
        /// </summary>
        public static string EULATitle {
            get {
                return ResourceManager.GetString("EULATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitBtn {
            get {
                return ResourceManager.GetString("ExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishBtn {
            get {
                return ResourceManager.GetString("FinishBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup completed successfully.
        /// </summary>
        public static string InstallationCompleteMessage {
            get {
                return ResourceManager.GetString("InstallationCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Complete.
        /// </summary>
        public static string InstallationCompleteTitle {
            get {
                return ResourceManager.GetString("InstallationCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string InstallBtn {
            get {
                return ResourceManager.GetString("InstallBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immo Pro Installer.
        /// </summary>
        public static string InstallerName {
            get {
                return ResourceManager.GetString("InstallerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being installed.
        /// </summary>
        public static string InstallingCaption {
            get {
                return ResourceManager.GetString("InstallingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        public static string InstanceNameLabel {
            get {
                return ResourceManager.GetString("InstanceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextBtn {
            get {
                return ResourceManager.GetString("NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immo Pro desktop application is installed successfully.
        /// </summary>
        public static string OnSuccessfulInstallationCaption {
            get {
                return ResourceManager.GetString("OnSuccessfulInstallationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressPercentage {
            get {
                return ResourceManager.GetString("ProgressPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing previous version.
        /// </summary>
        public static string RemovingPreviousVersion {
            get {
                return ResourceManager.GetString("RemovingPreviousVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immo Pro has been successfully removed from your computer..
        /// </summary>
        public static string UninstallationCompleteMessage {
            get {
                return ResourceManager.GetString("UninstallationCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstallation Complete.
        /// </summary>
        public static string UninstallationCompleteTitle {
            get {
                return ResourceManager.GetString("UninstallationCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string UninstallBtn {
            get {
                return ResourceManager.GetString("UninstallBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immo Pro Uninstaller.
        /// </summary>
        public static string UninstallerViewHeading {
            get {
                return ResourceManager.GetString("UninstallerViewHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being uninstalled.
        /// </summary>
        public static string UninstallingCaption {
            get {
                return ResourceManager.GetString("UninstallingCaption", resourceCulture);
            }
        }
    }
}
